### ISSUE TITLE
@rune-ts/server sass deprecation warning

### ISSUE THREAD

**Issue by nabi-chan** [marpple/rune#2]
안녕하세요. 우연한 계기로 멋진 라이브러리를 쓰고 있습니다. 감사합니다.
다만 지속적으로 sass 관련 deprecation warning이 표시되고 있어 해당 이슈가 노운인지 질문드리고자 합니다.

현재 @rune-ts/server 는 의존성으로 `sass@^1.71.1` 를 참조하고 있는것으로 보이는데요.
하지만 sass 라이브러리가 1.18.0 으로 마이너 범프 되며([#](https://github.com/sass/dart-sass/releases/tag/1.80.0)) `@import` 문법이 deprecated 되어 @rune-ts/server 를 사용하여 신규로 의존성을 설치하는 경우 `sass@1.18.0` 이후의 버전이 설치되어 지속적으로 deprecation warning이 표시되고 있습니다.

이부분을 고치려면 해당 문법이 deprecation이 되지 않은 `[1.79.6](https://github.com/sass/dart-sass/releases/tag/1.79.6)` 버전으로 의존성 버전을 고정하거나 다른 방법을 찾아봐야 할듯 싶습니다.

원래는 server 레포지토리에 남겨야하는 내용이지만, 해당 레포지토리가 공개되어있지 않아 부득이하게 해당 레포에 이슈 작성하는점 양해 부탁드립니다.
그럼 좋은 하루 되시길 바랍니다.

**Comment by Jeong-Jae-Hun** [comment]
@nabi-chan 님, 안녕하세요!
마플 개발팀 정재훈입니다!

우선 답장이 느려서 정말 죄송합니다!
그리고 라이브러리를 사용해주셔서 정말 감사합니다.

말씀해주신 이슈는 마플 개발팀 내부에서도 이슈가 제기됐었는데요.

결론부터 말씀드리자면 deprecation 된 해당 규칙을 이제는 최대한 사용하지 않아야할 것 같습니다.
이는 css에서 권장하는 방법을 sass팀이 채택한 것으로 보이며 추후 미래 호환성이나 sass 최신 버전의 지원을 받기 위해서도 sass팀이 제시한 방법으로 스타일을 짜야할 것 같습니다.

정확하게 어떤 warning이 발생하셨는지는 모르겠지만 저희 팀에서 발생한 경고에 대한 참고 페이지는 아래와 같으니 참고 바라겠습니다!

[mixed-decls](https://sass-lang.com/documentation/breaking-changes/mixed-decls/)

좋은 내용 남겨주셔서 정말 감사합니다.
